version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8055:8080"
  forum_db:
    container_name: forum_db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "8091:5432"
  forum_service:
    container_name: forum_service
    restart: always
    build:
      context: "./ForumService"
      dockerfile: "Dockerfile"
    ports:
      - "8090:80"
    depends_on:
      - rabbitmq
      - forum_db
  account_db:
    container_name: account_db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "8092:5432"
  account_service:
    container_name: account_service
    restart: always
    build:
      context: "./AccountService"
      dockerfile: "Dockerfile"
    ports:
      - "8093:80"
    depends_on:
      - rabbitmq
      - account_db
  post_db:
    container_name: post_db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "8094:5432"
  post_service:
    container_name: post_service
    restart: always
    build:
      context: "./PostService"
      dockerfile: "Dockerfile"
    ports:
      - "8095:80"
    depends_on:
      - rabbitmq
      - account_db
  api_gateway:
    container_name: api_gateway
    restart: always
    build:
      context: "./API Gateway"
      dockerfile: "Dockerfile"
    ports:
      - "8100:80"
    depends_on:
        - forum_service
        - account_service