version: "3.7"

services:
  prototype:
    container_name: prototype
    restart: always
    build:
      context: "./Microservice Prototype"
      dockerfile: "Dockerfile"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      Logging__Console__FormatterName: "simple"
    ports:
      - "8090:80"