version: "3.7"

services:
  prototype:
    container_name: prototype
    restart: always
    build:
      context: "./Microservice Prototype"
      dockerfile: "Dockerfile"
    ports:
      - "8090:80"