version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  forum_db:
    container_name: forum_db
    restart: always
    image: postgres
    ports:
      - "8091:5432"
  forum_service:
    container_name: forum_service
    restart: always
    build:
      context: "./ForumService"
      dockerfile: "ForumServiceAPI/Dockerfile"
    ports:
      - "8090:80"
    depends_on:
      - rabbitmq
      - forum_db
  producer:
    container_name: producer
    restart: always
    build:
      context: "./Microservice Producer"
      dockerfile: "Dockerfile"
    ports:
      - "8095:80"
    depends_on:
      - rabbitmq