version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  forum_service:
    container_name: forum_service
    restart: always
    build:
      context: "./ForumService"
      dockerfile: "ForumServiceAPI/Dockerfile"
    ports:
      - "8090:80"
    depends_on:
      - rabbitmq
  producer:
    container_name: producer
    restart: always
    build:
      context: "./Microservice Producer"
      dockerfile: "Dockerfile"
    ports:
      - "8091:80"
    depends_on:
      - rabbitmq
#  consumer:
#    container_name: consumer
#    restart: always
#    build:
#      context: "./Microservice Consumer"
#      dockerfile: "Dockerfile"
#    ports:
#      - "8092:80"
#  prototype:
#    container_name: prototype
#    restart: always
#    build:
#      context: "./Microservice Prototype"
#      dockerfile: "Dockerfile"
#    ports:
#      - "8090:80"