name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mindhawk/advanced-software-individual-project

      - name: Build and publish Account Service Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./AccountService
          push: true
          tags: mindhawk/advanced-software-individual-project:accountservice
          labels: ${{ steps.meta.output.labels }}

      - name: Build and publish Auth Service Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./ForumService
          push: true
          tags: mindhawk/advanced-software-individual-project:forumservice
          labels: ${{ steps.meta.output.labels }}

      - name: Build and publish API Gateway Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "./API Gateway"
          push: true
          tags: mindhawk/advanced-software-individual-project:apigateway
          labels: ${{ steps.meta.output.labels }}