name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "AccountService/**"
      - "Api Gateway/**"
      - "ForumService/**"

jobs:

  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            AccountService:
              - 'AccountService/**'
            ApiGateway:
              - 'Api Gateway/**'
            ForumService:
              - 'ForumService/**'
            PostService:
              - 'PostService/**'

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mindhawk/advanced-software-individual-project

      - name: Build and publish Account Service Docker image
        if: steps.filter.outputs.AccountService == 'true'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./AccountService
          push: true
          tags: mindhawk/advanced-software-individual-project-account-service:accountservice
          labels: ${{ steps.meta.output.labels }}

      - name: Build and publish Forum Service Docker image
        if: steps.filter.outputs.ForumService == 'true'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./ForumService
          push: true
          tags: mindhawk/advanced-software-individual-project-forum-service:forumservice
          labels: ${{ steps.meta.output.labels }}
          
      - name: Build and publish Post Service Docker image
        if: steps.filter.outputs.PostService == 'true'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./PostService
          push: true
          tags: mindhawk/advanced-software-individual-project-post-service:postservice
          labels: ${{ steps.meta.output.labels }}

      - name: Build and publish API Gateway Docker image
        if: steps.filter.outputs.ApiGateway == 'true'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "./API Gateway"
          push: true
          tags: mindhawk/advanced-software-individual-project-api-gateway:apigateway
          labels: ${{ steps.meta.output.labels }}